MakeupOnlineShop/urls.py
from django.urls import path ,include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('Order.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Order/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('cart/',views.order_list_view, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('finalize-order/', views.finalize_order, name='finalize_order'),
    path('order-complete/<int:order_id>/', views.order_complete_view, name='order_complete'),
    path('prev', views.PrevView.as_view(), name='previous_orders'),
]

home/urls.py
from django.urls import path
from . import views
from .views import HomeView
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('',views.HomeView.as_view(), name='home'),
    path('products/<int:pk>',views.ProductDetailsView.as_view(), name='details'),
    path('login',views.LoginInterfaceView.as_view(), name='login'),
path('logout',views.LogoutInterfaceView.as_view(), name='logout'),
    path('signup',views.SignupInterfaceView.as_view(), name='signup'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/change-password/', auth_views.PasswordChangeView.as_view(
        template_name='profile_password.html',
        success_url='/profile/'
    ), name='change_password'),
]

Order/models.py
from django.db import models
from django.contrib.auth.models import User
from home.models import Product
from datetime import timedelta

class Order(models.Model):
    user = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    address = models.TextField()
    delivered = models.BooleanField(default=False)
    payment_status = models.CharField(max_length=20, choices=[
        ('pending', 'Pending'),
        ('paid', 'Paid'),
        ('failed', 'Failed')
    ], default='pending')

    def __str__(self):
        return f"Order #{self.id} by {self.user.username}"

    @property
    def total_price(self):
        return sum(item.price * item.quantity for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)  # price at purchase time

    def __str__(self):
        return f"{self.quantity} x {self.product.name} in Order #{self.order.id}"

    @property
    def total_price(self):
        return self.price * self.quantity

Order/forms.py
from django import forms
from .models import Product

class AddToCartForm(forms.Form):
    product_id = forms.IntegerField(widget=forms.HiddenInput)
    quantity = forms.IntegerField(min_value=1, initial=1)

class FinalizeOrderForm(forms.Form):
    address = forms.CharField(widget=forms.Textarea, required=True)

Order/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Product, Order, OrderItem
from .forms import AddToCartForm , FinalizeOrderForm
from django.contrib.auth.decorators import login_required
from django.utils.timezone import now
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        form = AddToCartForm(request.POST)
        if form.is_valid():
            quantity = form.cleaned_data['quantity']

            order, created = Order.objects.get_or_create(
                user=request.user,
                delivered=False,
                payment_status='pending',
            )

            item, created = OrderItem.objects.get_or_create(
                order=order,
                product=product,
                defaults={'quantity': quantity, 'price': product.price}
            )
            if not created:
                item.quantity += quantity
                item.save()

            return redirect('cart')

    else:
        form = AddToCartForm(initial={'product_id': product_id})

    return render(request, 'buy_product.html', {'form': form, 'product': product})

@login_required
def order_complete_view(request, order_id):
    order = get_object_or_404(Order, id=order_id, user=request.user)

    if request.method == 'POST':
        order.payment_status = 'paid'
        order.save()
        return render(request, 'payment_success.html', {'order': order})


    return render(request, 'pay.html', {'order': order})

@login_required
def order_list_view(request):
    all_orders = Order.objects.filter(user=request.user).order_by('-created_at')
    paid_orders = Order.objects.filter(
        user=request.user,
        payment_status='paid'
    ).order_by('-created_at')

    pending_order = Order.objects.filter(
        user=request.user,
        payment_status='pending',
        delivered=False,
        items__isnull=False
    ).order_by('-created_at').first()

    failed_orders = all_orders.filter(payment_status='failed')


    return render(request, 'order_cart.html', {
        'paid_orders': paid_orders,
        'pending_order': pending_order,
        'failed_orders': failed_orders,
    })
@login_required
def finalize_order(request):
    try:
        order = Order.objects.get(user=request.user, delivered=False, payment_status='pending')
    except Order.DoesNotExist:
        return redirect('cart')

    if request.method == 'POST':
        form = FinalizeOrderForm(request.POST)
        if form.is_valid():
            order.address = form.cleaned_data['address']
            order.save()
            return redirect('order_complete', order_id=order.id)

    else:
        form = FinalizeOrderForm(initial={'address': order.address})

    return render(request, 'finalize_order.html', {'form': form, 'order': order})


class PrevView(LoginRequiredMixin, TemplateView):
    template_name = 'last_orders.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['paid_orders'] = Order.objects.filter(
            user=self.request.user,
            payment_status='paid'
        ).order_by('-created_at')
        return context

Order/templates/bought_products.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'order_style.css' %}">

<div class="container mt-5" dir="rtl">
    <h2 class="text-center mb-4">سفارش‌های من</h2>

    {% if paid_orders %}
    <h4 class="text-center mb-4 colored_title">✅ سفارش‌های پرداخت‌شده</h4>
    {% for order in paid_orders %}
        {% include 'user_order.html' with order=order %}
    {% endfor %}
    {% endif %}

    <a href="{% url 'finalize_order' %}" class="btn btn-success mt-4">ثبت نهایی </a>

</div>
{% endblock %}

Order/templates/buy_product.html
{% extends 'index.html' %}
{% block content %}
    <html lang="fa" dir="rtl">
<div class="container mt-5 d-flex justify-content-center">

    <div class="card shadow" style="width: 25rem">
        <div class="row g-0">
            <div class="col-4">
                <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="{{ product.name }}">
            </div>
            <div class="col-8">
                <div class="card-body">
                    <h6 class="card-title text-success"> به سبد خرید اضافه شد</h6>
                    <p class="card-text mb-2">{{ product.name }}</p>

                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-sm btn-outline-success w-100 mt-2">افزودن مجدد</button>
                    </form>

                    <a href="{% url 'cart' %}" class="btn btn-sm btn-primary w-100 mt-2">مشاهده سبد خرید</a>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}
</html>

Order/templates/finalize_order.html
{% extends 'index.html' %}
{% block content %}     
    <html lang="fa" dir="rtl">
<div class="container mt-5">
    <h3>ثبت نهایی سفارش</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">ثبت سفارش</button>
    </form>
</div>
{% endblock %}
</html>

Order/templates/last_orders.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'order_style.css' %}">

<div class="container mt-5" dir="rtl">
    <h2 class="text-center mb-4">سفارش های من</h2>
{% for order in paid_orders %}
    {% include 'user_order.html' with order=order %}
{% endfor %}
</div>
{% endblock %}

Order/templates/order_cart.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'order_style.css' %}">

<div class="container mt-5" dir="rtl">
    <h2 class="text-center mb-4">سفارش من</h2>


    {% if pending_order %}
        <h4 class="text-center mb-4 colored_title">🕒 سفارش در انتظار پرداخت</h4>
        {% include 'user_order.html' with order=pending_order %}
        <div class="d-flex justify-content-between mt-3">
            <a href="{% url 'home' %}" class="btn btn-outline-secondary px-4">افزودن به لیست</a>
            <a href="{% url 'finalize_order' %}" class="btn btn-success px-4">ثبت نهایی</a>
        </div>
    {% else %}
        <p class="text-center text-muted">هنوز سفارشی ثبت نکرده‌اید.</p>
        <div class="text-center">
            <a href="{% url 'home' %}" class="btn btn-primary">بازگشت به فروشگاه</a>
        </div>
        <h4 class="text-center mb-4 colored_title mt-5">📦 سفارش‌های قبلی</h4>
        {% for order in paid_orders %}
            {% include 'user_order.html' with order=order %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

Order/templates/pay.html
{%  extends 'index.html' %}
{% block content %}
    <html lang="fa" dir="rtl">
    
<div class="container mt-4">
    <h3>پرداخت سفارش #{{ order.id }}</h3>
    <p>مبلغ قابل پرداخت: {{ order.total_price }} تومان</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">پرداخت</button>
    </form>
</div>
{% endblock %}
</html>

Order/templates/payment_success.html
{% extends 'index.html' %}
{% block content %}
    <html lang="fa" dir="rtl">
<div class="container mt-4">
    <div class=" text-center mb-4 colored_title alert alert-success">پرداخت با موفقیت انجام شد.</div>
    <p>شماره سفارش: <strong>#{{ order.id }}</strong></p>
    <p>وضعیت پرداخت: <strong>{{ order.get_payment_status_display }}</strong></p>
    <a href="{% url 'cart' %}" class="btn btn-primary mt-3">مشاهده سبد خرید</a>
</div>
{% endblock %}
</html>

Order/templates/user_order.html
<div class="card order-card mb-4" dir="rtl">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span> سفارش شماره {{ order.id }}</span>
        <span class="badge
            {% if order.payment_status == 'paid' %} bg-success
            {% elif order.payment_status == 'pending' %} bg-warning text-dark
            {% else %} bg-danger {% endif %}">
            {{ order.get_payment_status_display }}
        </span>
    </div>
    <div class="card-body">
        <p><strong> تاریخ:</strong> {{ order.created_at|date:"Y/m/d - H:i" }}</p>
        <p><strong> آدرس:</strong> {{ order.address }}</p>
        <p><strong> تحویل داده شده:</strong> {{ order.delivered|yesno:" بله,❌ خیر" }}</p>

        <div class="table-responsive order-table mt-3">
            <table class="table table-bordered text-center">
                <thead>
                    <tr>
                        <th>محصول</th>
                        <th>تعداد</th>
                        <th>قیمت واحد</th>
                        <th>جمع کل</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in order.items.all %}
                    <tr>
                        <td class="product-info">
                            <img src="{{ item.product.image.url }}" width="60" height="60" alt="{{ item.product.name }}">
                            <span>{{ item.product.name }}</span>
                        </td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.price|floatformat:"0" }} تومان</td>
                        <td>{{ item.total_price|floatformat:"0" }} تومان</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <p class="order-total mt-3">💰 مبلغ کل: {{ order.total_price|floatformat:"0" }} تومان</p>

        {% if order.payment_status == 'pending' %}
            <div class="text-end mt-2">
                <a href="{% url 'order_complete' order.id %}" class="btn btn-outline-primary btn-sm">پرداخت سفارش</a>
            </div>
        {% endif %}
    </div>
</div>